### ISSUE TITLE
Unsupported protocol (GPGME::Error)

### ISSUE THREAD

**Issue by loopj** [ConradIrwin/dotgpg#5]
```
$ dotgpg cat development.env
/Library/Ruby/Gems/2.0.0/gems/gpgme-2.0.7/lib/gpgme/ctx.rb:398:in `decrypt_verify': Unsupported protocol (GPGME::Error)
    from /Library/Ruby/Gems/2.0.0/gems/gpgme-2.0.7/lib/gpgme/crypto.rb:172:in `block in decrypt'
    from /Library/Ruby/Gems/2.0.0/gems/gpgme-2.0.7/lib/gpgme/ctx.rb:71:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/gpgme-2.0.7/lib/gpgme/crypto.rb:170:in `decrypt'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/dir.rb:58:in `block in decrypt'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/dir.rb:56:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/dir.rb:56:in `decrypt'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/cli.rb:95:in `block in cat'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/cli.rb:94:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/lib/dotgpg/cli.rb:94:in `cat'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/dotgpg-0.4.2/bin/dotgpg:5:in `<top (required)>'
    from /usr/bin/dotgpg:23:in `load'
    from /usr/bin/dotgpg:23:in `<main>'
```

**Comment by pRizz** [comment]
I had the same issue. dotgpg should gracefully handle this instead of crashing.
I fixed it with `brew install gpg`, as said in the Getting Started chapter.

Looks like an old issue :]
